### ISSUE TITLE
It had certain flaws that I found out.

### ISSUE THREAD

**Issue by PGautam27** [Srinidhi182/shellsort#1]
autorotation. Dark theme problem and enable to view added elements after a certain size. And also I need to kill the app in order to delete the sorted elements.

**Comment by PGautam27** [comment]
You could check out the problems once. And note it down and put it down here

**Comment by Srinidhi182** [comment]
Okay thanks !

**Comment by PGautam27** [comment]
ya now I'll close this issue then. If you have any updates that to be made just open up an issue. I'll look into it.
